language: node_js

sudo: false

branches:
  only:
    - master
    - develop
    - cli

os:
  - linux
  - windows

node_js:
  - "10"
  - "12"

script:
  - npm run test:coverage

after_success:
  - npm run codecov
